name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        run: npm install && npm run build

      - name: Push
        run: |
          mkdir -p "$HOME/.ssh"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > "$HOME/.ssh/id_rsa"
          touch "$HOME/.ssh/known_hosts"

          chmod 700 "$HOME/.ssh"
          chmod 600 "$HOME/.ssh/id_rsa"
          chmod 600 "$HOME/.ssh/known_hosts"

          ssh-keyscan -t rsa github.com >> "$HOME/.ssh/known_hosts"

          eval $(ssh-agent -s)
          ssh-add "$HOME/.ssh/id_rsa"
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "ActionsBot"

          cd dist
          git init
          git add .
          git commit -m "Deploying ${GITHUB_SHA}"
          git remote set-url origin git@github.com:TrueCarry/avatarcropper.git
          git remote -v
          git push origin HEAD:gh-pages --force
